// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_EH4K3Xp7FsLjcUSQPNF_qhh_JNoayl0',
    appId: '1:233345350967:web:123c4a5184415cd1b06eb2',
    messagingSenderId: '233345350967',
    projectId: 'earnage-566e7',
    authDomain: 'earnage-566e7.firebaseapp.com',
    storageBucket: 'earnage-566e7.appspot.com',
    measurementId: 'G-NYN8M467SC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBnjf97Q_2n0uJGpK02OCFrR4JC_D0EZI',
    appId: '1:233345350967:android:cc7ed1b6d2c79311b06eb2',
    messagingSenderId: '233345350967',
    projectId: 'earnage-566e7',
    storageBucket: 'earnage-566e7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBc-2jp8ticK7aWeqkYk0vm9BiqSwr025M',
    appId: '1:233345350967:ios:d5cae0cbfa997f98b06eb2',
    messagingSenderId: '233345350967',
    projectId: 'earnage-566e7',
    storageBucket: 'earnage-566e7.appspot.com',
    iosClientId: '233345350967-8b3ckvhftjmnra9k4o26pvc09li6fh5j.apps.googleusercontent.com',
    iosBundleId: 'com.example.earnage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBc-2jp8ticK7aWeqkYk0vm9BiqSwr025M',
    appId: '1:233345350967:ios:d5cae0cbfa997f98b06eb2',
    messagingSenderId: '233345350967',
    projectId: 'earnage-566e7',
    storageBucket: 'earnage-566e7.appspot.com',
    iosClientId: '233345350967-8b3ckvhftjmnra9k4o26pvc09li6fh5j.apps.googleusercontent.com',
    iosBundleId: 'com.example.earnage',
  );
}
